### PR TITLE
#23 Add Job Opportunities to Jobs Accordion

### PR DESCRIPTION
**Pull request by Markj89**
Enhances #23 

Screen Shot 2021-05-11 at 10 48 26 PM
Screen Shot 2021-05-11 at 10 49 03 PM

You can select which jobs to post and they'll show under the Accordion.
**This is a temporary fix**

The layout needs to be changed, I'm building a sketch prototype and will post it later. For now, this will do.

### CODE REVIEW

**Comment by itsmattsoria** [comment]
I agree, I think maybe we need to reconsider how the positions are laid out at the bottom there, but one issue I see with this solution is that with multiple job posts with lengthy descriptions being dropped into that accordion it's a loooooooot of information crammed into an accordion, and the styling is a bit subtle for the separation of job posts, and as well it's duplicate content to what shows up below: https://share.mattsoria.com/Screen-Recording-2021-05-12-10-13-24/

What if we gave the full job postings below (https://user-images.githubusercontent.com/3435026/117202624-a392f300-adb3-11eb-8e88-619750d35020.png) IDs and then just listed them in the accordion as anchor links that when clicked on jump you down to the full listing below?

**Comment by itsmattsoria** [comment]
One more note on this — I dig the solution you implemented to allow postings to be added to the accordion, but wondered if we could possibly even cut out that step — is there ever a time that they *wouldn't* want a job posting to show up in the accordion? If not then I'd say cut out the field from the Jobs page accordions and just automatically show them there. We could maybe handle this as a shortcode or something there. Just a thought, but the way you have it implemented is also works!

**Comment by Markj89** [comment]
Hey Matt, 

Sorry for the late response. The anchors is a good idea, I originally thought of using excerpts and then clicking to a new page for the job opportunities, rather than having them below the fold. However, I noticed the post type isn't visible. Do you think this is a good idea?

**Comment by Markj89** [comment]
Hey @itsmattsoria,

So I made the Job Post Type public and instead of showing it all on the `/join-us/`, it will be an excerpt.

**Comment by itsmattsoria** [comment]
Hey @Markj89 — sorry, been a busy week, but I should be able to get to it tonight or tomorrow!

**Comment by itsmattsoria** [comment]
@Markj89 — sorry again! Finally getting a chance to take a look at these now, will review and update soon!

**Comment by itsmattsoria** [comment]
@Markj89 okay, this looks good! I thought it'd be good to add breadcrumbs to the single job template so there's a way to get see where you are and clear path back to the join-us page, so I added that, but otherwise I think this is good to go. Do you want me to merge this and push it up to production?

**Comment by Markj89** [comment]
Yeah the Bread crumbs is a good idea.

You can set it up to production. 

Thank you

**Comment by itsmattsoria** [comment]
@Markj89 will do!

**Comment by itsmattsoria** [comment]
@Markj89 okay, this is up and ready to be used!

**Pull request merged**
