### PR TITLE
Press Page

### PR DESCRIPTION
**Pull request by Markj89**
# Press Page Post type Added
- New template part

### CODE REVIEW

**Comment by poopsplat** [comment]
@Markj89 — could you share a DB dump with me so I can preview what the new work looks like with the new page/content? Feel free to email it to me if that's the best way to share — thanks!

**Comment by poopsplat** [comment]
@Markj89 — made some updates here as well. Did some cleanup for the markup and the styles, and adjusted some of the styling a bit as well if that's okay — just kinda fixed up some styling of the tabs, spacing, etc. One immediate question I have that doesn't seem to be considered here but am curious if you have already discussed with the crew, is where this new press page will be listed in the site nav? Should it just go after Support Us in the main site nav? Or listed in the footer somewhere perhaps? We'll have to make some adjustments for either of those scenarios before we push it up live.

**Comment by Markj89** [comment]
@poopsplat, I haven't brought up where they want the page to be listed in the navigation. I think they're mostly looking to have the page up for now and they'll be able to direct users to it by direct link. 

As for the tabs and styling, I tried going off of the Sketch file that was sent over, There didn't seem to any pages similar.

**Comment by poopsplat** [comment]
@Markj89 — right on, that sounds fine for now. If they end up wanting to add it to the main nav or the footer we can do that down the line. 

As for the styling etc — yeah, there wasn't really anything in the design to build this from fully, but I think it was pretty close the way you made it, I did just make a few small adjustments so when you have a chance take a look and let me know if you think this is good to go!

**Comment by Markj89** [comment]
I will take a look at the styling this afternoon and get back to you before 5.

**Comment by Markj89** [comment]
The tabs aren't working. I'm assuming you just changed the styling, correct ? If so, it looks good.

Should we add `rel="nofollow"` to the Ahrefs?

**Comment by poopsplat** [comment]
@Markj89 — did you rerun gulp after you pulled down? If not you'll be getting the js from whatever branch you came from. They were working on my end, which is why I think that may be the case — if not, let me know and I'll look into it. Yeah, that's a good call. I didn't put it in initially because I wasn't sure if they would always be external links or sometimes be internal links. If you know they will always be external links then go ahead and make that change. Otherwise we should probably check if the url is internal or external.

**Comment by Markj89** [comment]
@poopsplat Hey, sorry for not responding. I was able to reload the Gulpfile. It looks good, I don't see any issues with it.

**Comment by poopsplat** [comment]
@Markj89 — no worries. Excellent! Any thoughts about the above comment about the links in news/press?

>Yeah, that's a good call. I didn't put it in initially because I wasn't sure if they would always be external links or sometimes be internal links. If you know they will always be external links then go ahead and make that change. Otherwise we should probably check if the url is internal or external.

**Comment by Markj89** [comment]
I think we should add `target="_blank". selector instead

**Comment by Markj89** [comment]
Disregard my last comment. `target="_blank"` is already in there. So we're good to go.

**Comment by poopsplat** [comment]
@Markj89 — okay! I just made sure `target="_blank"` was applied to all of the links and added `rel="noopener"` to them as well. I can deploy this whenever you say the word!

**Comment by Markj89** [comment]
Hey @poopsplat, 

Any reason why this is closed? Did you push your PR?

**Comment by poopsplat** [comment]
@Markj89 —nah, this PR is still open, just the issue (#12) that was referencing it was closed. I was just waiting for your call to deploy it — is it good to deploy today?

**Comment by Markj89** [comment]
Yeah as long the default image is a good idea?

I'm wary that they'd want to change it so I should just keep it as a default. Give me an hour to check

**Comment by Markj89** [comment]
Sorry, I mixed up which PR, this is ready to go out.

**Comment by poopsplat** [comment]
@Markj89 — you got it!

**Comment by poopsplat** [comment]
@Markj89 — okay, this has been deployed and is ready for content on production!

**Pull request merged**
